repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]

  - repo: local
    hooks:
      - id: compile-requirements
        name: Compile requirements.txt
        entry: bash compile-requirements.sh
        language: system
        types: [text]