version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: development
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - ENV=development
