version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - ENV=development
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
