"""base schema

Revision ID: 0099504470f9
Revises:
Create Date: 2025-09-16 22:04:21.260767

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0099504470f9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "species",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("scientific_name", sa.Text(), nullable=False),
        sa.Column("authors_abbrev", sa.Text(), nullable=True),
        sa.Column("publication_year", sa.Integer(), nullable=True),
        sa.Column("lineage", sa.Text(), nullable=True),
        sa.Column("family", sa.Text(), nullable=True),
        sa.Column("group_name", sa.Text(), nullable=True),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column("lum_mycelium", sa.Boolean(), nullable=True),
        sa.Column("lum_basidiome", sa.Boolean(), nullable=True),
        sa.Column("lum_stipe", sa.Boolean(), nullable=True),
        sa.Column("lum_pileus", sa.Boolean(), nullable=True),
        sa.Column("lum_lamellae", sa.Boolean(), nullable=True),
        sa.Column("lum_spores", sa.Boolean(), nullable=True),
        sa.Column("type_country", sa.Text(), nullable=True),
        sa.Column(
            "distribution_regions",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("mycobank_index_fungorum_id", sa.BigInteger(), nullable=True),
        sa.Column("mycobank_type", sa.Text(), nullable=True),
        sa.Column("ncbi_taxonomy_id", sa.BigInteger(), nullable=True),
        sa.Column("inaturalist_taxon_id", sa.BigInteger(), nullable=True),
        sa.Column("iucn_redlist", sa.Text(), nullable=True),
        sa.Column("unite_taxon_id", sa.BigInteger(), nullable=True),
        sa.Column("references_raw", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("inaturalist_taxon_id"),
        sa.UniqueConstraint("ncbi_taxonomy_id"),
        sa.UniqueConstraint("scientific_name", name="uq_species_scientific_name"),
        sa.UniqueConstraint("unite_taxon_id"),
    )
    with op.batch_alter_table("species", schema=None) as batch_op:
        batch_op.create_index(
            "idx_species_distribution",
            ["distribution_regions"],
            unique=False,
            postgresql_using="gin",
        )
        batch_op.create_index("idx_species_family", ["family"], unique=False)
        batch_op.create_index("idx_species_lineage", ["lineage"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("institution", sa.String(length=150), nullable=True),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("password", sa.String(length=150), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "species_photos",
        sa.Column("species_id", sa.BigInteger(), nullable=False),
        sa.Column("photo_id", sa.BigInteger(), nullable=False),
        sa.Column("medium_url", sa.Text(), nullable=False),
        sa.Column("original_url", sa.Text(), nullable=True),
        sa.Column("license_code", sa.Text(), nullable=True),
        sa.Column("attribution", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), server_default="iNaturalist", nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["species_id"], ["species.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("species_id", "photo_id", name="pk_species_photo"),
    )
    with op.batch_alter_table("species_photos", schema=None) as batch_op:
        batch_op.create_index(
            "idx_species_photos_species", ["species_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("species_photos", schema=None) as batch_op:
        batch_op.drop_index("idx_species_photos_species")

    op.drop_table("species_photos")
    op.drop_table("users")
    with op.batch_alter_table("species", schema=None) as batch_op:
        batch_op.drop_index("idx_species_lineage")
        batch_op.drop_index("idx_species_family")
        batch_op.drop_index("idx_species_distribution", postgresql_using="gin")

    op.drop_table("species")
    # ### end Alembic commands ###
