"""create taxon model

Revision ID: 157cdfd07bf2
Revises: 5b5b4853e6f2
Create Date: 2025-09-23 10:05:47.887337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157cdfd07bf2'
down_revision = '5b5b4853e6f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxonomies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('species_id', sa.BigInteger(), nullable=False),
    sa.Column('classification', sa.Text(), nullable=False),
    sa.Column('synonyms_current_name', sa.Text(), nullable=False),
    sa.Column('synonyms_basionym', sa.Text(), nullable=False),
    sa.Column('rank', sa.Text(), nullable=False),
    sa.Column('name_type', sa.Text(), nullable=False),
    sa.Column('gender', sa.Text(), nullable=False),
    sa.Column('name_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taxonomies', schema=None) as batch_op:
        batch_op.create_index('idx_taxonomies_species', ['species_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxonomies', schema=None) as batch_op:
        batch_op.drop_index('idx_taxonomies_species')

    op.drop_table('taxonomies')
    # ### end Alembic commands ###
