"""create_references_table

Revision ID: 27db13c64910
Revises: 6e68e6de4532
Create Date: 2026-04-01 21:32:48.309126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27db13c64910'
down_revision = '6e68e6de4532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doi', sa.Text(), nullable=False),
    sa.Column('apa', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species_references',
    sa.Column('species_id', sa.BigInteger(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['references.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('species_id', 'reference_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species_references')
    op.drop_table('references')
    # ### end Alembic commands ###
