"""create taxon basionym field

Revision ID: 3f6ae7a6610e
Revises: d2852c1fb09a
Create Date: 2026-04-13 21:15:10.810541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6ae7a6610e'
down_revision = 'd2852c1fb09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxonomies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basionym', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxonomies', schema=None) as batch_op:
        batch_op.drop_column('basionym')

    # ### end Alembic commands ###
