"""create authors on taxon

Revision ID: 3fbbb6bd3621
Revises: 60576506de5e
Create Date: 2025-09-24 00:50:34.390439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fbbb6bd3621'
down_revision = '60576506de5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxonomies', schema=None) as batch_op:
        batch_op.drop_column('name_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxonomies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_status', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
