"""alter_species_table

Revision ID: 444f3b9a1a8b
Revises: e0383ee632a3
Create Date: 2026-04-01 21:21:16.367200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '444f3b9a1a8b'
down_revision = 'e0383ee632a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_index('idx_species_distribution', postgresql_using='gin')
        batch_op.drop_column('distribution')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distribution', postgresql.ARRAY(postgresql.ENUM('EU', 'NA', 'SA', 'CA', 'PA', 'CH', 'JP', 'MS', 'AU', 'AF', name='distribution_enum')), server_default=sa.text("'{}'::distribution_enum[]"), autoincrement=False, nullable=False))
        batch_op.create_index('idx_species_distribution', ['distribution'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
