"""create lumm atribute on species_photos model

Revision ID: 5b5b4853e6f2
Revises: 0099504470f9
Create Date: 2025-09-17 19:12:47.979329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5b4853e6f2'
down_revision = '0099504470f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species_photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lumm', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species_photos', schema=None) as batch_op:
        batch_op.drop_column('featured')
        batch_op.drop_column('lumm')

    # ### end Alembic commands ###
