"""create authors on taxon

Revision ID: 60576506de5e
Revises: cf619c32cbf3
Create Date: 2025-09-24 00:49:03.612350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60576506de5e'
down_revision = 'cf619c32cbf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxonomies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authors', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxonomies', schema=None) as batch_op:
        batch_op.drop_column('authors')

    # ### end Alembic commands ###
