"""create_references_table

Revision ID: 6e68e6de4532
Revises: 7da59e6c757d
Create Date: 2026-04-01 21:31:41.381246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e68e6de4532'
down_revision = '7da59e6c757d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_column('references_raw')

    with op.batch_alter_table('species_distributions', schema=None) as batch_op:
        batch_op.drop_index('idx_species_distributions_distribution_id')
        batch_op.drop_index('idx_species_distributions_species_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species_distributions', schema=None) as batch_op:
        batch_op.create_index('idx_species_distributions_species_id', ['species_id'], unique=False)
        batch_op.create_index('idx_species_distributions_distribution_id', ['distribution_id'], unique=False)

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('references_raw', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
