"""alter_species_table

Revision ID: 7da59e6c757d
Revises: 444f3b9a1a8b
Create Date: 2026-04-01 21:23:52.848536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da59e6c757d'
down_revision = '444f3b9a1a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species_distributions',
    sa.Column('species_id', sa.BigInteger(), nullable=False),
    sa.Column('distribution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['distribution_id'], ['distributions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('species_id', 'distribution_id')
    )
    with op.batch_alter_table('species_distributions', schema=None) as batch_op:
        batch_op.create_index('idx_species_distributions_distribution_id', ['distribution_id'], unique=False)
        batch_op.create_index('idx_species_distributions_species_id', ['species_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species_distributions', schema=None) as batch_op:
        batch_op.drop_index('idx_species_distributions_species_id')
        batch_op.drop_index('idx_species_distributions_distribution_id')

    op.drop_table('species_distributions')
    # ### end Alembic commands ###
