"""create taxon model

Revision ID: 86693726d2a4
Revises: 157cdfd07bf2
Create Date: 2025-09-23 10:18:13.873006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86693726d2a4'
down_revision = '157cdfd07bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxonomies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synonyms', sa.Text(), nullable=False))
        batch_op.drop_column('synonyms_basionym')
        batch_op.drop_column('synonyms_current_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxonomies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synonyms_current_name', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('synonyms_basionym', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('synonyms')

    # ### end Alembic commands ###
