"""add mushroom_observer_name_id to species

Revision ID: 90232da00fd3
Revises: f7ac63a2ec51
Create Date: 2026-04-29 13:22:24.511202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90232da00fd3'
down_revision = 'f7ac63a2ec51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mushroom_observer_name_id', sa.BigInteger(), nullable=True))
        batch_op.create_unique_constraint(None, ['mushroom_observer_name_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('mushroom_observer_name_id')

    # ### end Alembic commands ###
