"""create characteristics fields

Revision ID: 94de0c72afcc
Revises: 3f6ae7a6610e
Create Date: 2026-04-14 21:15:57.894021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94de0c72afcc'
down_revision = '3f6ae7a6610e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species_characteristics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cultivation_possible', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('iucn_assessment_year', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('iucn_assessment_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species_characteristics', schema=None) as batch_op:
        batch_op.drop_column('iucn_assessment_url')
        batch_op.drop_column('iucn_assessment_year')
        batch_op.drop_column('cultivation_possible')

    # ### end Alembic commands ###
