"""create_url_references_table

Revision ID: b1338a1c988a
Revises: 27db13c64910
Create Date: 2026-04-01 22:01:16.177855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1338a1c988a'
down_revision = '27db13c64910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('references', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('references', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
