"""remove unused fields

Revision ID: cf619c32cbf3
Revises: 86693726d2a4
Create Date: 2025-09-23 21:59:01.970796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf619c32cbf3'
down_revision = '86693726d2a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_column('authors_abbrev')
        batch_op.drop_column('publication_year')

    with op.batch_alter_table('taxonomies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('years_of_effective_publication', sa.Text(), nullable=True))
        batch_op.alter_column('classification',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('synonyms',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('name_type',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('name_status',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('rank')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxonomies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.alter_column('name_status',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('name_type',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('synonyms',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('classification',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('years_of_effective_publication')

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_year', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('authors_abbrev', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
