"""fixin taxon-species relation 1:1

Revision ID: d27a9f70d1bf
Revises: 3fbbb6bd3621
Create Date: 2025-09-24 22:07:35.180241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27a9f70d1bf'
down_revision = '3fbbb6bd3621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxonomies', schema=None) as batch_op:
        batch_op.drop_index('idx_taxonomies_species')
        batch_op.create_unique_constraint('uq_taxonomies_species_id', ['species_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxonomies', schema=None) as batch_op:
        batch_op.drop_constraint('uq_taxonomies_species_id', type_='unique')
        batch_op.create_index('idx_taxonomies_species', ['species_id'], unique=False)

    # ### end Alembic commands ###
