"""create_url_references_table

Revision ID: d2852c1fb09a
Revises: b1338a1c988a
Create Date: 2026-04-01 22:03:47.196772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2852c1fb09a'
down_revision = 'b1338a1c988a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('references', schema=None) as batch_op:
        batch_op.alter_column('doi',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('apa',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('references', schema=None) as batch_op:
        batch_op.alter_column('apa',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('doi',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
