"""create_outdated_flag_mycobank

Revision ID: f2c8684f0de7
Revises: d9a1b2c3d4e5
Create Date: 2026-04-01 18:58:27.345728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2c8684f0de7'
down_revision = 'd9a1b2c3d4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_outdated_mycobank', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_column('is_outdated_mycobank')

    # ### end Alembic commands ###
