"""add observations table

Revision ID: f4677ed01b68
Revises: d1e2f3a4b5c6
Create Date: 2026-04-28 22:20:17.906925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4677ed01b68'
down_revision = 'd1e2f3a4b5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('species_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('location_obscured', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=True),
    sa.Column('quality_grade', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_observation_source_external_id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index('idx_observation_source', ['source'], unique=False)
        batch_op.create_index('idx_observation_species_id', ['species_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index('idx_observation_species_id')
        batch_op.drop_index('idx_observation_source')

    op.drop_table('observations')
    # ### end Alembic commands ###
