"""add last_inaturalist_sync_at to species

Revision ID: f7ac63a2ec51
Revises: f4677ed01b68
Create Date: 2026-04-29 13:06:06.379295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ac63a2ec51'
down_revision = 'f4677ed01b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_inaturalist_sync_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_column('last_inaturalist_sync_at')

    # ### end Alembic commands ###
