name: Lançar nova release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag da imagem no GHCR (ex: latest ou v1.2.3)"
        required: true
        default: latest

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    name: Deploy on self-hosted runner
    runs-on: self-hosted

    env:
      APP_DIR: ${{ vars.APP_DIR }}
      IMAGE: ${{ vars.APP_IMAGE }}
      SERVICE: api

    steps:
      - name: Login on GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update repository
        working-directory: ${{ env.APP_DIR }}
        run: |
          git config --global --add safe.directory "${{ env.APP_DIR }}"
          git pull --ff-only origin main

      - name: Deploy with Docker Compose
        working-directory: ${{ env.APP_DIR }}
        run: |
          docker compose pull "${SERVICE}"
          docker compose up -d --no-deps "${SERVICE}"

      - name: Check initial logs
        run: docker logs --tail=30 lumm-server || true

      - name: Clean up old images
        run: docker image prune -f
