name: Lançar nova release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag da imagem no GHCR (ex: latest ou v1.2.3)"
        required: true
        default: latest

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    name: Deploy on self-hosted runner
    runs-on: self-hosted

    env:
      APP_DIR: /home/alenz/G2BC-web-apps/lumm/LUMM-server
      IMAGE: ghcr.io/g2bc/lumm-server

    steps:
      - name: Login no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull da imagem
        run: docker pull "$IMAGE:${{ github.event.inputs.tag }}"

      - name: Deploy com docker compose
        working-directory: ${{ env.APP_DIR }}
        run: |
          echo "Atualizando LUMM Server..."
          docker compose down
          docker compose up -d
          echo "✅ Novo container em execução:"
          docker ps --filter "name=lumm-server"

      - name: Verificar logs iniciais
        run: docker logs --tail=30 lumm-server || true

      - name: Limpeza de imagens antigas
        run: docker image prune -f
